trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-16
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 40
    maxParallelTrials: 5
    enableTrialEarlyStopping: TRUE
    params:
      - parameterName: max-depth
        type: INTEGER
        minValue: 3
        maxValue: 10
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: learning-rate
        type: DOUBLE
        minValue: 0.0001
        maxValue: 0.5
        scaleType: UNIT_LOG_SCALE
      - parameterName: n-estimators
        type: INTEGER
        minValue: 1
        maxValue: 1000
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: gamma
        type: DOUBLE
        minValue: 0
        maxValue: 0.5
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: min-child-weight
        type: INTEGER
        minValue: 1
        maxValue: 6
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: max-delta-step
        type: INTEGER
        minValue: 0
        maxValue: 10
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: subsample
        type: DOUBLE
        minValue: 0.5
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: colsample-bytree
        type: DOUBLE
        minValue: 0.5
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: colsample-bylevel
        type: DOUBLE
        minValue: 0.5
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: reg-alpha
        type: DOUBLE
        minValue: 0.00001
        maxValue: 100
        scaleType: UNIT_LOG_SCALE
      - parameterName: reg-lambda
        type: DOUBLE
        minValue: 0.00001
        maxValue: 100
        scaleType: UNIT_LOG_SCALE
      - parameterName: scale-pos-weight
        type: DOUBLE
        minValue: 0.01
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE