trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-16
  hyperparameters:
    maxTrials: 40
    maxParallelTrials: 5
    resumePreviousJobId: tune_isicTrainer_20190316_220344
    enableTrialEarlyStopping: TRUE